version: '3.8'

services:
  rpg_database:
    build:
      context: ..
      dockerfile: project_root/rpg_database/Dockerfile
    image: padster2012/rpg_database:latest
    container_name: rpg_database
    environment:
      POSTGRES_DB: rpg
      POSTGRES_USER: rpg_user
      POSTGRES_PASSWORD: rpg_pass
    ports:
      - "5432:5432"
  
  rpg_web_frontend:
    build:
      context: ..
      dockerfile: project_root/rpg_web_frontend/Dockerfile
    image: padster2012/rpg_web_frontend:latest
    container_name: rpg_web_frontend
    depends_on:
      - rpg_database
    ports:
      - "5000:5000"
  
  rpg_content_creator:
    build:
      context: ..
      dockerfile: project_root/rpg_content_creator/Dockerfile
    image: padster2012/rpg_content_creator:latest
    container_name: rpg_content_creator
    depends_on:
      - rpg_database
    ports:
      - "5001:5000"
  
  rpg_content_api:
    build:
      context: ..
      dockerfile: project_root/rpg_content_api/Dockerfile
    image: padster2012/rpg_content_api:latest
    container_name: rpg_content_api
    depends_on:
      - rpg_database
    ports:
      - "5002:5000"
