version: '3.8'

services:
  rpg_database:
    image: postgres:13
    container_name: rpg_database
    environment:
      POSTGRES_DB: rpg
      POSTGRES_USER: rpg_user
      POSTGRES_PASSWORD: rpg_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpg_user"]
      interval: 30s
      timeout: 10s
      retries: 5

  rpg_web_frontend:
    build:
      context: ..
      dockerfile: project_root/rpg_web_frontend/Dockerfile
    image: padster2012/rpg_web_frontend:latest
    container_name: rpg_web_frontend
    depends_on:
      rpg_database:
        condition: service_healthy
    ports:
      - "5000:5000"

  # rpg_content_creator:
  #   build:
  #     context: ..
  #     dockerfile: project_root/rpg_content_creator/Dockerfile
  #   image: padster2012/rpg_content_creator:latest
  #   container_name: rpg_content_creator
  #   depends_on:
  #     rpg_database:
  #       condition: service_healthy
  #   ports:
  #     - "8001:8001"
