version: '3.8'

services:
  rpg_database:
    build:
      context: ..
      dockerfile: project_root/rpg_database/Dockerfile
    image: padster2012/rpg_database:latest
    container_name: rpg_database
    environment:
      POSTGRES_DB: rpg
      POSTGRES_USER: rpg_user
      POSTGRES_PASSWORD: rpg_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpg_user -d rpg"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rpg_web_frontend:
    build:
      context: ..
      dockerfile: project_root/rpg_web_frontend/Dockerfile
    image: padster2012/rpg_web_frontend:latest
    container_name: rpg_web_frontend
    depends_on:
      rpg_database:
        condition: service_healthy
    ports:
      - "5000:5000"

  rpg_content_creator:
    build:
      context: ..
      dockerfile: project_root/rpg_content_creator/Dockerfile
    image: padster2012/rpg_content_creator:latest
    container_name: rpg_content_creator
    depends_on:
      rpg_database:
        condition: service_healthy
    ports:
      - "8001:8001"

  rpg_content_api:
    build:
      context: ..
      dockerfile: project_root/rpg_content_api/Dockerfile
    image: padster2012/rpg_content_api:latest
    container_name: rpg_content_api
    depends_on:
      rpg_database:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
